export const ON_SELECT_TESTAMENT = 'ON_SELECT_TESTAMENT';
export const ON_SELECT_BOOK = 'ON_SELECT_BOOK';
export const ON_SELECT_CHAPTER = 'ON_SELECT_CHAPTER';
export const ON_SELECT_TITLE = 'ON_SELECT_TITLE';
export const ON_SELECT_VERSE = 'ON_SELECT_VERSE';
