export const ON_SELECT_TESTAMENT = 'ON_SELECT_TESTAMENT';
export const ON_SELECT_BOOK = 'ON_SELECT_BOOK';
export const ON_SELECT_CHAPTER = 'ON_SELECT_CHAPTER';
export const ON_SELECT_TITLE = 'ON_SELECT_TITLE';
export const ON_SELECT_VERSE = 'ON_SELECT_VERSE';

export const ON_FETCH_TESTAMENTS_SUCCESS = 'ON_FETCH_TESTAMENTS_SUCCESS';
export const ON_FETCH_TESTAMENTS_FAILURE = 'ON_FETCH_TESTAMENTS_FAILURE';
export const ON_FETCH_BOOKS_SUCCESS = 'ON_FETCH_BOOKS_SUCCESS';
export const ON_FETCH_BOOKS_FAILURE = 'ON_FETCH_BOOKS_FAILURE';
export const ON_FETCH_CHAPTERS_SUCCESS = 'ON_FETCH_CHAPTERS_SUCCESS';
export const ON_FETCH_CHAPTERS_FAILURE = 'ON_FETCH_CHAPTERS_FAILURE';
